run:
  concurrency: 4
  go: "1.20"

issues:
  exclude-use-default: false

linters:
  enable-all: false
  disable-all: false
  fast: false
  enable:
    # tencent necessary
    - cyclop # 圈复杂度
    - bodyclose # 检查HTTP Res Body 是否 Close 了
    - lll # 检查一行代码是否过长
    - funlen # 检查函数里面的行数
    - revive # 提供类型 golint 的功能
    # personal necessary

linters-settings:
  cyclop:
    skip-tests: true
    max-complexity: 20
    package-average: 5
  lll:
    tab-width: 1
    line-length: 120 # 公司规范也是这样
  funlen:
    lines: 80
    statements: 40
    ignore-comments: false
  revive:
    severity: error
    rules:
      - name: package-comments
        disabled: false
        exclude: [""]

      - name: exported
        disabled: false
        exclude: [""]
        arguments:
          - "checkPrivateReceivers"